# Generated by Django 5.1.3 on 2024-11-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_managment_app', '0002_subadmintable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubadminTable',
            new_name='ManageSubAdminTable',
        ),
    ]
