# Generated by Django 5.1.3 on 2024-11-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_managment_app', '0004_subadmintable_delete_managesubadmintable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmintable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='water_managment_app.logintable'),
        ),
    ]
