# Generated by Django 5.1.3 on 2024-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_managment_app', '0005_subadmintable_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontable',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
