# Generated by Django 4.2.17 on 2024-12-29 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water_managment_app', '0006_connectiontable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='readertable',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='water_managment_app.areatable'),
        ),
        migrations.AlterField(
            model_name='readertable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='water_managment_app.logintable'),
        ),
    ]
